dependency:
  name: galaxy
  options:
    requirements-file: collections.yml

driver:
  name: docker

lint: |
  set -e
  ec
  yamllint --strict -c .yamllint .
  ansible-lint -x 106,701 .
  flake8 --ignore=E501

platforms:
  - name: instance
    image: debian:buster
    dockerfile: Dockerfile.j2
    override_command: false
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true

provisioner:
  name: ansible
  log: true

verifier:
  name: testinfra
