name: CI
on:  # yamllint disable-line rule:truthy
  - push
  - pull_request
jobs:
  test:
    name: Molecule
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install editorconfig-checker
          sudo ln --symbolic "$(which editorconfig-checker)" /usr/local/bin/ec
          python -m pip install molecule[docker,lint,test]

      - name: Run Molecule tests
        run: |
          make version
          make test
